apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n 
  template:
    metadata:
      labels:
        app: n8n 
    spec:
      securityContext:
        fsGroup: 1000 # www-data group ID
        runAsUser: 1000 # www-data user ID
        runAsGroup: 1000 # www-data group ID
      containers:
        - name: n8n 
          image: docker.n8n.io/n8nio/n8n:2.19.5
          ports:
            - containerPort: 9190

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: n8n_data
              mountPath: /home/node/.n8n 

          envFrom:
            - configMapRef:
                name: n8n_configmap

      volumes:
        - name: n8n_data
          persistentVolumeClaim:
            claimName: n8n_data-pvc
