apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n 
      
  template:
    metadata:
      labels:
        app: n8n 

    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000 
        runAsGroup: 1000 

      containers:
        - name: n8n 
          image: docker.n8n.io/n8nio/n8n:1.123.43

          ports:
            - containerPort: 3008
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: n8n_data
              mountPath: /home/node/.n8n 

          envFrom:
            - configMapRef:
                name: n8n_configmap
      
      restartPolicy: Always

      volumes:
        - name: n8n_data
          persistentVolumeClaim:
            claimName: n8n_data-pvc
