apiVersion: v1
data:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:05uAlADBfDEI2ZtZ63ztgg==,iv:vAfUYEBwGmmmeJkFI7XatWqS69y+Vftx3vsO5DfEwKk=,tag:CTbc6O7CpeD/D8OKKqrWqQ==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:kFOkNLstXKQ=,iv:qiQHuMGoHMBNMd0AM5qd9NlKDQqvdBtPTj01Wm3NGck=,tag:Mr4p8bbGvWVRHkiT3FKmfA==,type:str]
kind: Secret
metadata:
    name: grafana-env
sops:
    age:
        - recipient: age1ws023uxrlf5dkugely0w09tk7xsj5a6sc0234su5pjsna5063vdqzznhtx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YVkxNEl1Z0pMTlY4alNX
            MTdsbEtSVTlZUkZnclVOVENDZm40c1NYSVNZCmQ4N3hFNFI3RHJsM25lSXR0ZmRz
            Y2tZRkRhU2JsZkQ5ZjBFNWRVeFhXVEEKLS0tIHNiMTlvc1ZxKzVERzhZRkpVYjlt
            UFVraHUyZldXNXVPREl3Mlh2T1hWTDgKV1tn+Ol6jiH2FfhA0ZGxXJwuZ/aI5Zue
            EXTnBFGd+D4ft0UCRyO5n/fu6o1pFoX927nKobh9vG6ILj9QphE6LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T19:19:02Z"
    mac: ENC[AES256_GCM,data:Z5x82/B3Cbd01xMsOmTt68cgVqB0IyjzrvtNvxqLmjCY2fbNN/pxsCD9Bz8TBK6RG8nxHxkzqWwXpCZtNP42/tNcmSRTZnsl8Yg1QtHCXE2AI0ZvMtX8mVmsRS5l/SJMtCHTXn7b19VLqy1VGjUXyg9GVY7eWtQ+p6IFhFfOhAw=,iv:DMlDXXF5PCf6bylsVRcs5N+xtYLDHgde+ufUzxNqlq4=,tag:aJ8jHU9JT3pwtuGeDJr9sQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
