# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: grafana-env-secret.yaml
  userKey: GF_SECURITY_ADMIN_USER
  passwordKey: GF_SECURITY_ADMIN_PASSWORD
