apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap 
          
          ports:
            - containerPort: 3005
              protocol: TCP

    restartPolicy: Always
