apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:89vLrP1W02g=,iv:/pgxi8ghWQqdD34MGwGIm64dcWUGJg49OClaju593kc=,tag:1k7793AjseKROZ4h/ODF7A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:nggtUutU+kc=,iv:+BMmsgdHwL7XXyG5B5d4fcsfireI5sqB+/Jr8umcD8I=,tag:puIrGR5WK3LGBrwp45xHcQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1ws023uxrlf5dkugely0w09tk7xsj5a6sc0234su5pjsna5063vdqzznhtx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eSt5NVQxKzFXbDhkMG5o
            cC81TThEaDczVVpMZTNYdXpRTzZIWGRHYUUwClBaOXlMdWg4cDFRM0FKNmpKaDhZ
            QVk5SVdLZmJpKzltOTRzQm1oL0JlblkKLS0tIHN5MDF6U1BhaUtpUk5HOEJRdUNv
            SlNoYnFBK09WR0FMUW4zUGdJMHFQeXcKBd3X7n290n4OfgZ9cGp4wI+7uI3hlbAu
            zyqDNP48t7bg/n943T9UJAtgqZGGMkAtb3iXQ49vuRPU3JRGzkDHKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T15:48:06Z"
    mac: ENC[AES256_GCM,data:kAN6vUYlH8H0e+A9uFFVP8uNVb9fVuWuvCM5PfiawXz+M24NcNatS3rcmziGd58/jNR6KPMv9k8bYa3RxvkZ8weeykZVHCCa6tYklX1Gj93PQ7pfOgduESffzBxP2AB06Idr1nxHVwfGryaFaLhqfIV+2HmFMwqhTRLa2OtEsRA=,iv:jxa9e4aLkDEtOcGN88mtPk/1Vg8/oDenSXyHMGrskhA=,tag:Kw7Jh+PI7rUDGdUePCwUXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
